# Generated by Django 3.2.19 on 2024-09-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='difficulty',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
